[sdl]
fullscreen=false
fullresolution=Standard
windowresolution=1280x960

[cpu]
cycles=auto

[dosbox]
machine=svga_s3

[render]
scaler=normal2x

[serial]
serial1=nullmodem server:127.0.0.1 port:5000

[autoexec]
path=%PATH%;C:\BC\BIN
mount c "/Volumes/WindowsShare/MSDOS/C_DRIVE"
mount d "/Users/kevincarr/projects/C"
D:
cd \ZMGR
ZMGR.EXE run
exit
